feature_descriptions = {
    "age": ("Age", "Age of the patient in years", "Age is a major risk factor — older individuals are more prone to CAD."),
    "sex": ("Sex", "1 = Male, 0 = Female", "Males are generally at higher risk of CAD."),
    "cp": ("Chest Pain Type (cp)",
           "0 = Typical angina, 1 = Atypical angina, 2 = Non-anginal pain, 3 = Asymptomatic",
           "Chest pain type gives clues about cardiac-related symptoms."),
    "trestbps": ("Resting Blood Pressure (trestbps)",
                 "Measured in mm Hg on admission to the hospital",
                 "High blood pressure strains the heart and arteries, increasing CAD risk."),
    "chol": ("Serum Cholesterol (chol)",
             "Serum cholesterol in mg/dl",
             "High cholesterol levels contribute to plaque buildup in arteries."),
    "fbs": ("Fasting Blood Sugar > 120 mg/dl (fbs)",
            "1 = True, 0 = False",
            "Elevated fasting blood sugar is linked to diabetes, a CAD risk factor."),
    "restecg": ("Resting Electrocardiographic Results (restecg)",
                "0 = Normal, 1 = ST-T wave abnormality, 2 = Left ventricular hypertrophy",
                "Abnormal ECG readings can indicate heart strain or damage."),
    "thalach": ("Max Heart Rate Achieved (thalach)",
                "Measured during exercise stress test",
                "Lower max heart rate may indicate impaired heart function."),
    "exang": ("Exercise Induced Angina (exang)",
              "1 = Yes, 0 = No",
              "Indicates chest pain caused by exercise, a CAD indicator."),
    "oldpeak": ("Oldpeak",
                "ST depression induced by exercise relative to rest",
                "Measures possible blockage; higher values are concerning."),
    "slope": ("Slope of Peak Exercise ST Segment (slope)",
              "0 = Upsloping, 1 = Flat, 2 = Downsloping",
              "Downsloping ST is strongly linked to CAD."),
    "ca": ("Number of Major Vessels Colored by Fluoroscopy (ca)",
           "Range: 0–3",
           "More blocked vessels = higher CAD likelihood."),
    "thal": ("Thalassemia (thal)",
             "1 = Normal, 2 = Fixed defect, 3 = Reversible defect",
             "Abnormal thallium scan may indicate restricted blood flow to the heart.")
}
